ERROR 2024-10-27 15:53:38,745 log Internal Server Error: /accounts/create-user
Traceback (most recent call last):
  File "C:\Users\3ples\Desktop\__PROJECTMGMT__\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\3ples\Desktop\__PROJECTMGMT__\backend\venv\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "C:\Users\3ples\Desktop\__PROJECTMGMT__\backend\venv\lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "C:\Users\3ples\Desktop\__PROJECTMGMT__\backend\venv\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/accounts/create-user/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
